# Generated by Django 3.2.7 on 2021-09-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210925_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='crf_pk',
            new_name='crf_patient_pk',
        ),
    ]
